name: Build and Push Docker image to ECR

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2 # change to your region

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t airflow_with_deps:latest .

      - name: Tag Docker image
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/dev/airflow-images:airflow_with_deps
          docker tag airflow_with_deps:latest $IMAGE_URI

      - name: Push Docker image to ECR
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/dev/airflow-images:airflow_with_deps
          docker push $IMAGE_URI