name: Deploy to EC2

on:
  push:
    branches: [ deploy-aws ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" . ec2-user@3.106.117.175:/home/ec2-user/airflow_tuto

      - name: Deploy with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@3.106.117.175 '
            cd /home/ec2-user/airflow_tuto &&
            docker compose pull &&
            docker compose up -d --build
          '