name: Copy DAGS to GCP VM

on:
  push:
    branches: [ deploy-dags ]

jobs:
  copy-dags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: GCP auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Remove existing DAGS on GCP VM
        run: |
          gcloud compute ssh ${{ vars.GCP_VM_INSTANCE_NAME }} --zone ${{ vars.GCP_REGION }} -- "rm -rf  ~/airflow-deploy/dags/*"

      - name: Copy DAGS to GCP VM
        run: |
          gcloud compute scp --recurse dags/ ${{ vars.GCP_VM_INSTANCE_NAME }}:~/airflow-deploy/dags/ --zone ${{ vars.GCP_REGION }}